### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by julianomqs** [yury/fork-events#1]
Hey,

I saw your lib in a gist about nodemon/browsersync integration. Seems great.

I have just a few questions:

1) I noticed `app.js` (central point of my app) was not being watched, so I add:
`gulp.watch(['app.js'], server.refork);`
Do you think it is alright to do this?

2) I have this file structure:

```
example
    client
        component
            person.service.js
        person
            person-list.html
            person-list.controller.js
            person-edit.html
            person-edit.controller.js
        index.html
    server
        person
            person.controller.js
            person.routes.js
            person.model.js
    app.js
    gulpfile.js
    bower.json
    package.json      
```

My `gulp.watch` rules are:

```
gulp.watch(['server/**/*'], server.refork);
gulp.watch(['client/**/*.js'], server.refork);
gulp.watch(['client/**/*.css', 'client/**/*.html'], browserSync.reload);
```

Do you think these `watches` are alright?

Thank you.

**Comment by yury** [comment]
1. Yep, it is ok
2. For client assets (css and js) it is better to use `stream` 

`gulp.watch(['client/**/*.css'], browserSync.reload( { stream : true } ) );`

**Comment by julianomqs** [comment]
I was thinking, why reloading BrowserSync if server files (models, routes, etc) change?

IMO, reloading BrowserSync is only useful if you change frontend files. Am I wrong?

I was thinking about this workflow:

```
gulp serve task

fork app.js
start browsersync

watch backend files, if a file changes, refork app.js
watch frontend files, if a file changes, reload browsersync
```

What you think?

**Comment by yury** [comment]
Yep, you are right.

If you have time. It would be super useful to write this in readme :)
